services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn -b 0.0.0.0:8000 workspace.wsgi:application
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - pgdb

  pgdb:
    image: postgres:17
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pgdbdata:
  static_volume:
  media_volume:
